### PR TITLE
feat: capture document origin information

### LINKED ISSUE #213: Retaining Original SBOM format
**Background:**
Presently, when unserializing a document within the project, a notable challenge arises in preserving the original format of the document within its structure. This presents obstacles for subsequent processes that depend on the initial SBOM format information. Moreover, there's a consideration that additional optional metadata fields, such as the original SBOM payload hash, size, and file name, may also be worth retaining within the protobom document.

**Problem:**
1. **Loss of Original Format Information:** Following unserialization, the original SBOM format of the document isn't maintained within its structure, leading to difficulties for downstream processes in ascertaining the format.

**Explore Solutions:** (IMHO)
1. **Implementation of Format Retention:** Investigate potential approaches to incorporate a mechanism that preserves the original SBOM format information within the document structure post-unserialization.
   
2. **Function for Retrieving Original Format:** Consider the addition of getter and setter functions within the document structure to facilitate the setting and retrieval of the detected format, such as `doc.GetUnserializerFormat()` and `doc.SetUnserializerFormat(format)`.

3. **Consideration of a Free JSON Field:** Evaluate the feasibility and usefulness of including a free JSON field to accommodate additional metadata or custom information.

**Use Cases:**
1. **Serialization After Changes:** This feature is particularly beneficial for scenarios involving the serialization of the document format after modifications. Tools like diff or convert can leverage this information to automatically select the appropriate serializer for the original document format.
  
2. **Querying Capabilities:** Improved querying capabilities tied to a specific format streamline document handling based on format types.

**Technical Considerations:**
1. **Optimizing Auto-Detection Process:** Failure to specify a format during document conversion may result in inefficiencies, necessitating the auto-detection process to run twice: once for selecting the unserializer and again to determine the format for inversion.

### PR DESCRIPTION
**Pull request by ashearin**
Adds a sourceData message to capture information related to the source sbom during ingestion by protobom. The MetaData message has been updated to hold this new sourceData object which is populated as a part of `ParseStreamWithOptions`

A slightly modified version of solution proposed by @houdini91 in #213. 

Intended to close #213 

* Tests will be added once consensus on solution has been reached

### CODE REVIEW

**Comment by ashearin** [comment]
@puerco @jhoward-lm FYI

**Comment by ashearin** [comment]
Not sure why the `build-and-test` is saying the spec is out of date, I ran `task proto` along with everything else prior to submission.  

Tried running `make proto` again just now, along with the individual buf commands, but it resulted in no changes. Maybe a misconfiguration of my env?

**Comment by ashearin** [comment]
@jhoward-lm helped me get everything back in shape! Thanks!

**Review by puerco — APPROVED** [review]
Ah sorry about this @ashearin I reviewed this on a flight and the review didn't go through when I clicked the button. Sorry about the confusion with the previous approval. 

It's awesome to finally get this. There is a slight detail as the PR successfully lands a triple read on the document stream. But I think I know how we can fix it. I'll open a follow-up with a proposed solution.

**Review by puerco — CHANGES_REQUESTED** [review]
OK. Sorry about the confusion with the comments. I thought the initial review had gone in.

**Review by puerco — APPROVED** [review]
Thanks!!

**Pull request merged**
