### PR TITLE
protbom ref suggestion

### PR DESCRIPTION
**Pull request by houdini91**
Hi there, 
Suggesting to add the following documentation reference tables generated out of our loveable protobom protobuf structure,
You can review the current version in [ref](https://github.com/scribe-security/protobom/blob/ISSUE-162-overview-protobom-description-tables/docs/protobom-ref.md).

Related to [issue](https://github.com/bom-squad/protobom/issues/162)

@manifestori If we decide we want this doc i be happy if you help me integrate this in to our uber cool dev container ..

I would like to suggest the addition of documentation reference tables generated from our beloved Protobom protobuf structure. The current version of these tables can be reviewed [here](https://github.com/scribe-security/protobom/blob/ISSUE-162-overview-protobom-description-tables/docs/protobom-ref.md).

This suggestion is closely related to [issue #162](https://github.com/bom-squad/protobom/issues/162).

@manifestori , if the community decides to include this documentation, I would greatly appreciate your assistance in integrating it into our fantastic development container.

Here is an example of how I currently handle it:
```
docker run --rm   -v /home/mikey/scribe/DHS/protobom/docs:/out   -v /home/mikey/scribe/DHS/protobom/api/:/protos   pseudomuto/protoc-gen-doc --doc_opt=markdown,protobom-ref.md
```

### CODE REVIEW

**Comment by puerco** [comment]
Oh this is cool, what do you think about adding a presubmit check to ensure the docs don't go stale? SOmething like what we do with the protos themselves:

https://github.com/bom-squad/protobom/blob/52f2d4b5162dbd15efaf397c5254a3f426e94246/hack/verify-proto.sh#L18-L20

**Comment by dn-scribe** [comment]
@houdini91 , 
If we note all format specifc data in separate columns, this could enable us to automatically generate the "transfer function" of a whole translator ! 
The infomration neede would be the meaning of each field for each SBOM format:version.
Is there a way to autogenerate these columns or some labeling capability ?

**Comment by houdini91** [comment]
@dn-scribe, Customizing the pattern might involve forking the protoc-gen-doc project. Let's shift the discussion to the pertinent issue and focus the pull request on a straightforward integration with protoc-gen-doc, establishing a foundation for future enhancements.

I see this documentation more as reference tables rather than detailed specification documentation. While it should capture the specifications and translations, it may lack the higher-level logical translation logic that users might find valuable. It could be worthwhile to include links to relevant tables or fields in the reference table for additional context.

**Comment by houdini91** [comment]
@puerco i added a verify-doc file but i am thinking maybe i merge it in to the verify-proto.sh file?

**Comment by puerco** [comment]
Can you add `hack/verify-doc.sh` to the presubmits here?

https://github.com/bom-squad/protobom/blob/7ce33d43003d97ca5e1d20bddb65579c16b73e15/.github/workflows/go-build-and-test.yml#L24-L26

**Comment by manifestori** [comment]
@houdini91 Ill make time this week to finally go over your PR.

**Pull request closed without merging**
